version: "3.7"
services:
  mysql-db:
    image: ${DBNERD_CONTAINER_REGISTRY}/mysql-db:latest
    restart: always
    container_name: dbnerd-1_mysql
    environment:
      MYSQL_DATABASE: ${DBNERD_DB_NAME}
      MYSQL_USER: ${DBNERD_MYSQL_USER}
      MYSQL_PASSWORD: ${DBNERD_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DBNERD_MYSQL_PASSWORD}
    networks:
      - dbnerd-net
    volumes:
      - ~/dbnerd-1-data:/var/lib/mysql
  dbnerd-1:
    image: ${DBNERD_CONTAINER_REGISTRY}/dbnerd-1:latest
    container_name: dbnerd-1_webapp
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - dbnerd-net
    environment:
      DBNERD_MYSQL_USER: ${DBNERD_MYSQL_USER}
      DBNERD_MYSQL_PASSWORD: ${DBNERD_MYSQL_PASSWORD}
      DBNERD_MYSQL_URL: ${DBNERD_MYSQL_URL}
    ports:
      - "80:80"
networks:
  dbnerd-net:
