FROM maven:3.6.3 AS build
WORKDIR /app
COPY pom.xml ./pom.xml
RUN mvn -B -f pom.xml dependency:resolve-plugins dependency:resolve clean package > /dev/null
COPY src ./src
RUN mvn -B -Dmaven.test.skip clean package

FROM openjdk:8
WORKDIR /app
COPY --from=build /app/target/DBNerd-1*.war /usr/local/lib/DBNerd-1.war
EXPOSE 80
ENTRYPOINT ["java", "-jar", "/usr/local/lib/DBNerd-1.war"]
