version: "3.7"
services:
  mysql-db:
    build:
      context: mysql-db
      dockerfile: Dockerfile
    container_name: dbnerd-1_mysql
    environment:
      MYSQL_DATABASE: ${DBNERD_DB_NAME}
      MYSQL_USER: ${DBNERD_MYSQL_USER}
      MYSQL_PASSWORD: ${DBNERD_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DBNERD_MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost","-u","${DBNERD_MYSQL_USER}","--password=${DBNERD_MYSQL_PASSWORD}" ]
      interval: 2s
      timeout: 10s
      retries: 10
    networks:
      - dbnerd-net
  mvn-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: dbnerd-1_mvn-test
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - dbnerd-net
    environment:
      DBNERD_MYSQL_HOST: mysql-db
      DBNERD_DB_NAME: ${DBNERD_DB_NAME}
      DBNERD_MYSQL_USER: ${DBNERD_MYSQL_USER}
      DBNERD_MYSQL_PASSWORD: ${DBNERD_MYSQL_PASSWORD}
      DBNERD_MYSQL_URL: ${DBNERD_MYSQL_URL}
networks:
  dbnerd-net:
